#%RAML 1.0

title: ACME Banking HTTP API
version: 1.0
mediaType: application/json

types:
  MonetaryAmountData: !include schemas/MonetaryAmountData.json
  DurationData: !include schemas/DurationData.json
  AddressData: !include schemas/AddressData.json
  NewCustomerData: !include schemas/CustomerData.json
  NewOrganizationData: !include schemas/NewOrganizationData.json
  NewPersonData: !include schemas/NewPersonData.json
  CustomerData: !include schemas/CustomerData.json
  OrganizationData: !include schemas/OrganizationData.json
  PersonData: !include schemas/PersonData.json
  NewBankAccountRequestData: !include schemas/NewBankAccountRequestData.json
  BankAccountData: !include schemas/BankAccountData.json
  NewLoanRequestData: !include schemas/NewLoanRequestData.json
  LoanData: !include schemas/LoanData.json
  CustomerMemberResponse: OrganizationData | PersonData

traits:
  contentCacheable: !include traits/content-cacheable.raml

resourceTypes: 
  collection: !include resourceTypes/collection.raml
  member: !include resourceTypes/member.raml

securitySchemes:
  oauth2_0: !include securitySchemes/oauth2_0.raml
  
securedBy: oauth2_0

/customers:
  displayName: Customer Resource
  /corporate:
    post:
      description: Customer data created correctly for an Organization
      body: NewOrganizationData
  /commercial:
    post:
      description: Customer data created correctly for a Person
      body: NewPersonData

  /{customer_id}:
    type:
      member:
        get-response-type: CustomerMemberResponse
        get-response-example: 
          type: Person
          id: "!23456"
          lei: 54930084UKLVMY22DS16
          tax_id: "999999999"
          email: info@new.org
          given_name: Dirk
          family_name: Fabian
          gender: male
          birth_date: 1987-09-30
          address:
            address_country: US
            address_locality: CA
            postal_code: "90003"
    uriParameters:
      customer_id: string
    /accounts:
      type: 
        collection:
          response-type: BankAccountData
          request-type: NewBankAccountRequestData
      /{account_id}:
        type:
          member:
            get-response-type: BankAccountData
            get-response-example:
              id: my_account
              account_number: "12345667"
              accountType: standard
              amount: 
                value: 123.45
                currency: Euro
              lei: 54930084UKLVMY22DS16
              fees_and_comissions: no fees
              review_state: ""
              interest_rate: 12
              annual_interest_rate: 15
              minimum_inflow: 
                value: 1000
                currency: Euro
              overdraft_limit: 
                value: 500
                currency: Euro
        uriParameters:
          account_id: string
    /loans:
      type: 
        collection:
          response-type: LoanData
          request-type: NewLoanRequestData
      get:
        is: [ contentCacheable ]
      /{loan_id}:
        type:
          member:
            get-response-type: LoanData
            get-response-example:
              id: my_account
              account_number: "12345667"
              accountType: standard
              amount: 
                value: 500
                currency: Euro
              lei: 54930084UKLVMY22DS16
              fees_and_comissions: no fees
              review_state: ""
              interest_rate: 12
              annual_interest_rate: 15
              minimum_inflow: 
                value: 500
                currency: Euro
              overdraft_limit: 
                value: 500
                currency: Euro
              grace_period: 
                value: 12m
        uriParameters:
          loan_id: string
