/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * json2ts banking-schema.json
 */
export interface SampleBankingSchema {
  additionalProperties?: any;
  NewCustomerData?: CustomerData;
  CustomerData?: CustomerData;
  PersonData?: {
    address: AddressData;
    customerData?: CustomerData;
    id: string;
    title?: Titles;
    given_name: string;
    family_name: string;
    gender: "female" | "male";
    vat_id?: string;
    birth_date: string;
    death_date?: string;
    [k: string]: any;
  };
  BankAccountData?: {
    id: string;
    account_number: string;
    accountType: "standard" | "saver";
    amount: MonetaryAmountData;
    lei: string;
    fees_and_comissions: string;
    review_state: AccountReviewState;
    interest_rate: number;
    annual_interest_rate: number;
    minimum_inflow: MonetaryAmountData;
    [k: string]: any;
  };
  NewBankAccountRequestData?: {
    accountType: "standard" | "saver";
    [k: string]: any;
  };
  LoanData?: {
    id: string;
    account_number: string;
    accountType: "standard" | "saver";
    amount: MonetaryAmountData;
    lei: string;
    fees_and_comissions: string;
    review_state: LoanReviewState;
    interest_rate: number;
    annual_interest_rate: number;
    minimum_inflow: MonetaryAmountData;
    overdraft_limit: MonetaryAmountData;
    grace_period: DurationData;
    [k: string]: any;
  };
  NewLoanRequestData?: {
    category: string;
    amount: MonetaryAmountData;
    term: DurationData;
    interest_rate: number;
    down_payment: MonetaryAmountData;
    payment_amount: MonetaryAmountData;
    payment_frequency: number;
    review_state: NewLoanReviewState;
    [k: string]: any;
  };
  MonetaryAmountData?: MonetaryAmountData;
  [k: string]: any;
}
export interface CustomerData {
  address: AddressData;
  type: string;
  lei: string;
  tax_id: string;
  email: string;
  [k: string]: any;
}
export interface AddressData {
  address_country: string;
  address_locality?: string;
  address_region?: string;
  postal_code: string;
  street_address?: string;
  [k: string]: any;
}
export interface MonetaryAmountData {
  value: number;
  currency: string;
}
export interface DurationData {
  value: string;
  [k: string]: any;
}

export const enum Titles {
  Mister = "mr",
  Misses = "mrs",
  Ms = "ms",
  Doctor = "dr"
}
export const enum AccountReviewState {
  requested = "requested",
  cancelled = "cancelled",
  opened = "opened",
  closed = "closed"
}
export const enum LoanReviewState {
  requested = "requested",
  cancelled = "cancelled",
  underwriting = "underwriting",
  accepted = "accepted",
  opening = "opening",
  failed = "failed",
  closed = "closed"
}
export const enum NewLoanReviewState {
  requested = "requested",
  underwriting = "underwriting",
  rejected = "rejected",
  accepted = "accepted",
  repaying = "repaying",
  failed = "failed",
  closed = "closed"
}
